---
title: "Drawing pretty DAGs in R"
subtitle: "With ggdag"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 14:8
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 8, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)
library(flipbookr)
library(tidyverse)
library(ggdag)
```


```{r ggdag, echo = FALSE, include=FALSE}
mycoords <- list(
        x = c(x = 0, y = 1, a = 1, b = 0),
        y = c(x = 0, y = 1, a = 0, b = 1)
    )
dagify(y ~ x + a + b,
       x ~ a + b,
       exposure = "x",
       outcome = "y",
       coords = mycoords) %>% #BREAK 
  node_parents("x") %>% #BREAK
  ggplot() + #BREAK
  aes(x = x) +
  aes(y = y) + #BREAK
  geom_dag_point() + #BREAK
  geom_dag_edges() +
  aes(xend = xend) +
  aes(yend = yend) + #BREAK
  geom_dag_text(col = "white", size = 6) + #BREAK
  geom_dag_edges_link(arrow = grid::arrow()) + #BREAK
  aes(color = parent) + #BREAK
  theme_dag() + #BREAK
  scale_color_hue(
    breaks  = c("parent", "child")
    ) #BREAK
```

`r chunk_reveal("ggdag", break_type = "user")`


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 100%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
