<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="true" />

<title>HDAT9700: Matching for Causal Inference</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->


<link rel="stylesheet" href="css/tutorials.css" type="text/css" />

</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<p><img src="images/UNSW_2017_Big_Data_landscape.jpg" style="width:75.0%" /></p>
<div id="section-overview" class="section level2">
<h2>Overview</h2>
<p>Welcome to HDAT9700 Statistical Modelling II Chapter 3!</p>
<p><img src="https://youtu.be/cvb17LGNKQ4" /></p>
<p>This chapter focuses on the challenge of drawing <strong>causal inferences from observational data</strong>.</p>
<p>Previously, you learned about randomised control trials (RCTs), and different approaches to randomisation, including simple, block and stratified randomisation. RCTs are the gold standard design for estimating causal effects: because treatment assignment is under the researchers’ control, it is possible to balance the characteristics of treated and untreated individuals, therefore any difference in their outcomes can be ascribed to the effect of the treatment or intervention.</p>
<p>When analysing observational data (e.g. a cohort study or administrative data), treatment assignment is no longer under the researchers control. As a result, treated and untreated individuals may differ in ways related to the outcome, therefore it is not straightforward to ascribe differences in the outcome to the treatment.</p>
<p>In this chapter we will explore <strong>matching</strong> as a general approach used to improve causal inferences from observational data. In broad terms, matching is a preprocessing technique that relies on pruning or duplicating observations so that the treated and untreated groups are similar in terms of their background characteristics.</p>
<p>At the end of this chapter you will be able to</p>
<ol style="list-style-type: decimal">
<li>Understand the challenges of drawing causal inferences from observational data</li>
<li>Discuss the assumptions needed to estimate causal effects from observational data</li>
<li>Implement various approaches to matching using the R package <code>MatchIt</code></li>
</ol>
<div id="section-readings" class="section level3">
<h3>Readings</h3>
<div id="section-pre-reading" class="section level4">
<h4>Pre-reading</h4>
<p>The pre-reading (pre-viewing!) for this chapter is the video <em>Why Propensity Scores Should Not Be Used For Matching</em> presented by <a href="garyking.org">Professor Gary King</a> from Harvard University.</p>
<p><img src="https://youtu.be/rBv39pK1iEs?t=87" /></p>
</div>
<div id="section-reference-text" class="section level4">
<h4>Reference text</h4>
<p>The reference text for this chapter is “Matching as Nonparametric Preprocessing for Reducing Model Dependence in Parametric Causal Inference” by Daniel Ho, Kosuke Imai, Gary King and Elizabeth Stuart, available <a href="https://gking.harvard.edu/files/matchp.pdf">here</a>. This chapter also draws heavily on the work of Miguel Hernán and colleagues—references are provided at the end of the chapter.</p>
<p>So let’s get <em>started</em>!!</p>
</div>
</div>
</div>
<div id="section-what-is-causal-inference" class="section level2">
<h2>What is causal inference?</h2>
<p>The models that we fit as data scientists perform different functions and allow us to answer different questions. Statistical modeling tasks have been classified into three categories:</p>
<ol style="list-style-type: decimal">
<li>Description<br />
</li>
<li>Prediction<br />
</li>
<li>Causal inference</li>
</ol>
<p><strong>Descriptive</strong> models can answer questions such as <em>what are the characteristics of children who participate in an early childhood program?</em></p>
<p><strong>Predictive</strong> models can answer questions such as <em>what is the probability of on-track development following participation in an early childhood program?</em></p>
<p><strong>Causal models</strong> can answer questions such as <em>does participation in an early childhood program improve children’s development, on average?</em></p>
<p>Causal inference is the science of posing and answering causal questions, “<em>questions which predict certain features of the world if the world had been different</em>” (Hernán et al 2018)</p>
<hr />
<p>There are many frameworks for assessing causality, some of which you covered in HDAT9200 Statistical foundations for health data science. Classical frameworks include the Bradford Hill Criteria and Rothman’s sufficient-component cause model.</p>
<p>In this chapter we approach causal inference from the <strong>counterfactual framework</strong>. This approach lends itself to more formalised discussion and identification of causal effects. The literature on counterfactual theory pays scant lip service to classical epidemiological frameworks such as the Bradford Hill criteria, but nonetheless these are still relevant and useful.</p>
<div class="aside">
<h3 id="section-aside">Aside</h3>
<p>As a reminder, the <strong>Bradford Hill Criteria</strong> are listed below.</p>
<ol style="list-style-type: decimal">
<li>Strength (effect size)<br />
</li>
<li>Consistency (reproducibility)<br />
</li>
<li>Specificity<br />
</li>
<li>Temporality<br />
</li>
<li>Biological gradient<br />
</li>
<li>Plausibility<br />
</li>
<li>Coherence<br />
</li>
<li>Experiment<br />
</li>
<li>Analogy</li>
</ol>
</div>
<hr />
<div id="section-spurious-correlations" class="section level3">
<h3>Spurious correlations</h3>
<p>We are all familiar with the old adage that <em>correlation does not imply causation</em>. Spurious correlations abound:</p>
<p>Number of films Nicolas Cage appeared in correlates with Number of people who drowned by falling into a swimming-pool <span class="math inline">\(\rho=0.67\)</span></p>
<div class="figure">
<img src="images/spurious1.png" alt="" />
<p class="caption">Reproduced with permission from <a href="http://tylervigen.com" class="uri">http://tylervigen.com</a></p>
</div>
<p><strong>People who drowned after falling out of a fishing boat</strong> correlates with <strong>Marriage rate in Kentucky</strong> <span class="math inline">\(\rho=0.95\)</span></p>
<div class="figure">
<img src="images/spurious.png" alt="" />
<p class="caption">Reproduced with permission from <a href="http://tylervigen.com" class="uri">http://tylervigen.com</a></p>
</div>
<p>Of course we know that correlation does not imply causation. Nonetheless:</p>
<ul>
<li>In the absence of confounding, observational estimates and causal estimates are the same<br />
</li>
<li>With observational data, we can still pose and answer causal questions (provided sufficient background information is present)<br />
</li>
<li>Even RCTs can only provided measures of association—we are just more confident in interpreting these as causal because of the experimental design.<br />
</li>
<li>Causal inferences from a rich observational dataset can be more reliable than those from a sub-par RCT (especially if the RCT sample is small and treatment adherence is poor)</li>
</ul>
</div>
</div>
<div id="section-counterfactual-outcomes" class="section level2">
<h2>Counterfactual outcomes</h2>
<p>Counterfactual outcomes refer to outcomes under alternative treatments or scenarios. These treatments may not have happened in real life so counterfactual outcomes are usually hypothetical!</p>
<div id="section-an-example" class="section level4">
<h4>An example</h4>
<p>The table below gives an example of the development outcomes (On-track/vulnerable) we might observe for children, some of who attended an early childhood program:</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Developmental outcomes following program participation
</caption>
<thead>
<tr>
<th style="text-align:left;">
Child
</th>
<th style="text-align:left;">
Participated?
</th>
<th style="text-align:left;">
Outcome following non-participation
</th>
<th style="text-align:left;">
Outcome following participation
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Anne
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Barry
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Katie
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
</tbody>
</table>
<ul>
<li>For Anne and Katie, we only observe what happened given that they did participate in the program<br />
</li>
<li>For Barry, we only observe what happened given that he did not participate</li>
</ul>
<p>The counterfactual framework is based on the premise of knowing outcomes under both scenarios. This is a conceptual idea only: of course we can not observe the counterfactual, we must imagine we have the power to change history or to reverse time and rerun an experiment.</p>
<p>If this was possible we would observe the full data table:</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Developmental outcomes following program participation (observed counterfactuals)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Child
</th>
<th style="text-align:left;">
Participated?
</th>
<th style="text-align:left;">
Outcome following non-participation
</th>
<th style="text-align:left;">
Outcome following participation
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Anne
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Barry
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Katie
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
</tbody>
</table>
<ul>
<li>In this table the counterfactuals are filled in<br />
</li>
<li>We “observe” the outcome following non participation for Anne and Katie<br />
</li>
<li>We “observe” the outcome following participation for Barry</li>
</ul>
</div>
</div>
<div id="section-notation" class="section level2">
<h2>Notation</h2>
<p>In order to define a causal effect more rigorously, we need to introduce some notation.</p>
<p>Let <span class="math inline">\(A\)</span> denote a dichotomous <strong>a</strong>ction, exposure or treatment. Let <span class="math inline">\(A\)</span> take the value <span class="math inline">\(1\)</span> if an individual receives the treatment and <span class="math inline">\(0\)</span> if they are untreated. Note, we will assume dichotomous treatments thoughout this chapter, but treatments or interventions with multiple arms are of course possible.</p>
<p>Let <span class="math inline">\(Y_{a=1}\)</span> denote the observed outcome for treatment <span class="math inline">\(A=1\)</span>, and <span class="math inline">\(Y_{a=0}\)</span> denote the observed outcome for treatment <span class="math inline">\(A=0\)</span> The outcomes <span class="math inline">\(Y_{a=0}\)</span> and <span class="math inline">\(Y_{a=1}\)</span> are referred to as counterfacutal outcomes. They are called <em>counterfactual</em> because one of the outcomes is under a treatment counter to what was actually observed. The term <strong>potential outcomes</strong> is also used, because Anne could potentially receive either treatment.</p>
<p>Let <span class="math inline">\(L\)</span> denote a vector of observed pretreatment variables</p>
<hr />
<p>To summarise, we have:</p>
<ul>
<li><span class="math inline">\(A\)</span> treatment indicator<br />
</li>
<li><span class="math inline">\(Y_{a=x}\)</span> outcome under treatment <span class="math inline">\(x\)</span><br />
</li>
<li><span class="math inline">\(L\)</span> vector pretreatment variables</li>
</ul>
<hr />
<div class="family">
<h3 id="section-a-running-example">A running example…</h3>
<p>Let’s set up a running example.</p>
<p>Consider an early childhood intervention program <em><em>Helping Hands</em></em>. Helping Hands is designed to support vulnerable families with young children aged 0-4. The program includes tailored assistance from a trained staff member who can provide parenting training and help coordinate access to early childhood services including health and childcare services.</p>
<p>Answer the questions on causal effect notation below, with this example in mind.</p>
</div>
<p><div class="panel-heading tutorial-quiz-title">Quiz 1: Causal effects notation</div></p>
<div class="panel panel-default">
<div data-label="quiz1-1" class="tutorial-question panel-body">
<div id="quiz1-1-answer_container" class="shiny-html-output"></div>
<div id="quiz1-1-message_container" class="shiny-html-output"></div>
<div id="quiz1-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz1-2" class="tutorial-question panel-body">
<div id="quiz1-2-answer_container" class="shiny-html-output"></div>
<div id="quiz1-2-message_container" class="shiny-html-output"></div>
<div id="quiz1-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz1-3" class="tutorial-question panel-body">
<div id="quiz1-3-answer_container" class="shiny-html-output"></div>
<div id="quiz1-3-message_container" class="shiny-html-output"></div>
<div id="quiz1-3-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
<div id="section-defining-causal-effects" class="section level2" data-progressive="TRUE">
<h2>Defining Causal Effects</h2>
<p>Below is the table we saw earlier, relabelled with the notation we have just covered.</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Developmental outcomes following program participation (observed counterfactuals)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Child
</th>
<th style="text-align:left;">
A
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{a=0}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{a=1}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Anne
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Barry
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Katie
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
</tbody>
</table>
<div id="section-individual-causal-effect" class="section level3">
<h3>Individual causal effect</h3>
<p>Focusing on the first child Anne, we see that <span class="math inline">\(Y_{a=0} = \text{Vulnerable}\)</span>, whereas <span class="math inline">\(Y_{a=1} = \text{On-track}\)</span>. This tells us that participation in Helping Hands had an causal effect on Anne’s development.</p>
<p>In general, an individual causal effect is present when counterfactual outcomes differ, i.e. <span class="math display">\[
Y_{a=0} \ne Y_{a=1}
\]</span></p>
<div class="think">
<h3 id="section-pause-and-think">Pause and think…</h3>
<p>Is there an individual causal effect for Barry or Katie?</p>
</div>
</div>
<div id="section-population-causal-effect" class="section level3">
<h3>Population causal effect</h3>
<p>In practice, we can’t examine individual causal effects. Instead we focus on population causal effects.</p>
<p>We define <span class="math inline">\(P(Y(1)=1)\)</span> as the proportion of individuals experiencing the outcome <span class="math inline">\(Y\)</span> if <span class="math inline">\(A=1\)</span>. And <span class="math inline">\(P(Y(0)=1)\)</span> as the proportion of individuals experiencing the outcome <span class="math inline">\(Y\)</span> if <span class="math inline">\(A=0\)</span>.</p>
If these two proportions are different, the treatment <span class="math inline">\(A\)</span> has a causal effect on <span class="math inline">\(Y\)</span>, i.e. <span class="math display">\[
P(Y(0)=1) \ne P(Y(1)=1)
\]</span>
<div class="think">
<h3 id="section-pause-and-think-1">Pause and think…</h3>
<p>Is there a population causal effect of helping hands on development in the table below?</p>
</div>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Developmental outcomes following program participation (observed counterfactuals)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Child
</th>
<th style="text-align:left;">
A
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{a=0}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{a=1}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Anne
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Barry
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Katie
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Mikey
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Nuffy
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Deirdre
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
John
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Betty
</td>
<td style="text-align:left;width: 20em; ">
Yes
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
<td style="text-align:left;width: 35em; ">
Vulnerable
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Oliver
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
<tr>
<td style="text-align:left;width: 20em; font-weight: bold;">
Monica
</td>
<td style="text-align:left;width: 20em; ">
No
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
<td style="text-align:left;width: 35em; ">
On-track
</td>
</tr>
</tbody>
</table>
</div>
<div id="section-discussions-points" class="section level3">
<h3>Discussions points</h3>
<p>For the children listed in the table, 4/10 have on-track development if nobody participates in the program. If everybody particpates then 6/10 have on-track development.</p>
<p>So we have:</p>
<p><span class="math inline">\(P(Y(0)=1)=0.4\)</span><br />
<span class="math inline">\(P(Y(1)=1)=0.6\)</span></p>
<p><span class="math inline">\(P(Y(0)=1) \ne P(Y(1)=1)\)</span> therefore we can say there is a causal effect of program participation.</p>
</div>
<div id="section-causal-effect-measures" class="section level3">
<h3>Causal effect measures</h3>
<p>Causal effects can be measured on the additive or multiplicative scale:</p>
<p><strong>Additive scale</strong><br />
<span class="math inline">\(P(Y(1)=1) - P(Y(0)=1)\)</span></p>
<p><strong>Multiplicative scale</strong><br />
<span class="math inline">\(P(Y(1)=1)/P(Y(0)=1)\)</span></p>
<div class="think">
<h3 id="section-pause-and-think-2">Pause and think…</h3>
<p>In the example above, what is the causal effect on (i) the additive scale and (ii) the multiplicative scale?</p>
</div>
<p><div class="panel-heading tutorial-quiz-title">Quiz 2: Causal effect measures</div></p>
<div class="panel panel-default">
<div data-label="quiz2-1" class="tutorial-question panel-body">
<div id="quiz2-1-answer_container" class="shiny-html-output"></div>
<div id="quiz2-1-message_container" class="shiny-html-output"></div>
<div id="quiz2-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz2-2" class="tutorial-question panel-body">
<div id="quiz2-2-answer_container" class="shiny-html-output"></div>
<div id="quiz2-2-message_container" class="shiny-html-output"></div>
<div id="quiz2-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
</div>
<div id="section-quantities-of-interest" class="section level2" data-progressive="TRUE">
<h2>Quantities of interest</h2>
<div id="section-different-types-of-treatment-effect" class="section level3">
<h3>Different types of treatment effect</h3>
<p>Having set up this framework for causal inference, it is possible to focus on different treatment effects by comparing outcomes among different populations. Two treatment effects of particular interest are</p>
<ol style="list-style-type: decimal">
<li><p><strong>The Average Treatment Effect (ATE)</strong><br />
The ATE estimates the average effect of applying a treatment to the entire population</p></li>
<li><p><strong>Average Treatment effect among the Treated (ATT)</strong><br />
The ATT estimates the average effect of the treatment on <em>those who actually received the treatment</em></p></li>
</ol>
<p>These quantities are both valid, but may be more or less of interest depending on context. For example, if a treatment is very expensive and/or invasive, it is likely to be administered to targeted subgroups rather than whole populations, and therefore the ATT is of more interest. The ATE is more applicable in estimating the effect of broad-based interventions that are rolled out to whole populations.</p>
<div class="think">
<h3 id="section-pause-and-think-3">Pause and think…</h3>
<p>Which effect (ATT or ATE) would be more relevant when evaluating an intervention like Helping Hands?</p>
<p>Can you think of an example where (i) the ATE and (ii) the ATT would be more relevant?</p>
</div>
</div>
<div id="section-points-to-note" class="section level3">
<h3>Points to note…</h3>
<ul>
<li>A program like Helping Hands is unlikely to be rolled out to an entire population, rather a small number of known individuals will be treated. The Average Treatment effect among the Treated will therefore be more relevant.</li>
<li>The Average Treatment Effect would be more relevant for a public health awareness campaign that is rolled out nationally on TV, radio and other media. The aim will be to reach everyone in the population but the people running the campaign are unlikely to know exactly who has been ‘treated’ i.e. been exposed to the advertising.</li>
</ul>
</div>
</div>
<div id="section-randomisation" class="section level2">
<h2>Randomisation</h2>
<p>Randomised experiments were discussed in Chapter 1. Classical random experiments have three core characteristics:<br />
1. Large <span class="math inline">\(N\)</span><br />
2. Random selection of individuals from a population<br />
3. Random assignment of individuals to a treatment</p>
<p>When these three characteristics are present, any background characteristics should be distributed equally among the untreated (<span class="math inline">\(A=0\)</span>) and treated (<span class="math inline">\(A=1\)</span>) individuals.</p>
</div>
<div id="section-the-problem-with-observational-data" class="section level2" data-progressive="TRUE">
<h2>The problem with observational data</h2>
<p>In an observational study, the characteristics of a population are observed but there is no intervention by the researcher. Examples of observational studies include cross-sectional, case-control and cohort studies.</p>
<p>When the researcher doesn’t have control over treatment assignment it becomes more difficult to identify causal effects. You will probably have a good intuitive sense of why this is the case…</p>
<div id="section-pause-and-think-4" class="section level3">
<h3>Pause and think</h3>
<div class="family">
<h3 id="section-consider">Consider…</h3>
<p>…a cross-sectional study that gathered information in a community where some children participated in the Helping Hands program. Bivariate analysis showed that children who participated in Helping Hands had significantly lower child development scores at age five. Why would it be problematic to claim that Helping Hands had a causal effect on development from this data source?</p>
<p>Can you give another example of a scenario where causal claims from a cross-sectional dataset may be questionable?</p>
</div>
<div class="think">
<h3 id="section-can-you-draw-a-dag-to-describe-this-scenario">Can you draw a DAG to describe this scenario?</h3>
<p>Think back on last week’s lecture!</p>
</div>
</div>
<div id="section-possible-solution" class="section level3">
<h3>Possible solution</h3>
<p>Because the Helping Hands program is targeted towards ‘vulnerable’ families there are likely to be confounding background characteristics (L variables, in our notation) that increase the chances of taking part in the program and decrease the chances of on-track development. For vulnerable families, this might include things like education, employment, physical &amp; mental health, access to health services and other supports, parenting skills, and drug &amp; alcohol issues. In the DAG below these confounding factors have been grouped together into a single node: ‘pre-existing family vulnerabilities’.</p>
<p><img src="matching_files/figure-html/unnamed-chunk-1-1.png" width="624" /></p>
</div>
<div id="section-points-to-think-about" class="section level3">
<h3>Points to think about</h3>
<p>In the first scenario, assignment to the treatment—participation in Helping Hands—is not under the researchers control. Because the data are observational, we are just observing what has already happened, and as discussed above children who participated in Helping Hands may have different characteristics compared to those who do not. Crucially, these differing characteristics <em>may also relate to child development</em>. For example, Helping Hands participants might come from economically disadvantaged families, or families where there are drug or alcohol issues. The observed relationship between participation and development may be attributable to these other factors, therefore we can’t claim a causal effect of the program. What we can say is that Helping Hands participation is <strong>associated</strong> with lower development, which can be useful information depending on purpose of the modelling exercise (recall the different modelling aims discussed in Chapter 1, and the distinctions between describing, explaining and predicting).</p>
<p>A famous example where spurious causal claims were inferred from observation data is the <a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(97)11096-0/fulltext">Wakefield et al study</a>, published in the Lancet in 1998. In this study, the authors linked gastrointestinal disease and developmental regression to the measles, mumps, and rubella (MMR) vaccination. These results fueled doubts about the safety of the vaccine, triggering a reduction in vaccination levels in several countries. However, the results were based on an uncontrolled analysis of 12 children, all of whom were selected for having both outcomes. The lancet fully retracted the paper in 2010. You can read more about this study, its flaws, and the subsequent fallout <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3136032/">here</a>.</p>
<center>
<div class="figure">
<img src="images/wakefield.png" style="width:50.0%" alt="" />
<p class="caption">The retracted Wakefield Study</p>
</div>
</center>
<hr />
</div>
<div id="section-visualising-causation-versus-association" class="section level3">
<h3>Visualising causation versus association</h3>
<p>The figure below captures the distinction between causal analyses and observational analyses.</p>
<ul>
<li><p>To perform a causal analysis, we would like to replicate the situation where we compare outcomes for the entire population under treatment to the entire population under no treatment (i.e. compare counterfactual outcomes).</p></li>
<li><p>With observational data, what we actually compare is the subset of the population who got the treatment to the subset of the population that did not.</p></li>
</ul>
<div class="figure">
<img src="images/causation_association.png" alt="" />
<p class="caption">Observation versus causation (Adapted from <a href="https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/">Causal Inference</a> (2018, Ch1) by Hernán and Robins)</p>
</div>
<hr />
<p>It is still possible to make causal claims from observational data, under certain assumptions. Because these assumtions allow us to <em>identify</em> causal effects they are referred to as <strong>identifiability assumptions</strong>.</p>
</div>
</div>
<div id="section-practical-1" class="section level2" data-progressive="TRUE">
<h2>Practical 1</h2>
<div id="section-the-matchit-package" class="section level3">
<h3>The <code>MatchIt</code> package</h3>
<p><code>MatchIt</code> is an R package which implements non-parametric pre-processing matching methods. The package has been developed by Daniel Ho, Kosuke Imai, Gary King and Elizabeth Stuart. Full documentation is available <a href="http://gking.harvard.edu/matchit">online</a> or by typing <code>help("MatchIt")</code> in the R console.</p>
<p><code>MatchIt</code> includes:</p>
<ul>
<li>Support for multiple sophisticated matching techniques<br />
</li>
<li>Inbuilt procedures for assessing balance<br />
</li>
<li>Integration with other R functionality</li>
</ul>
</div>
<div id="section-getting-started" class="section level3">
<h3>Getting started</h3>
<p>The <code>MatchIt</code> package has already been installed in the <code>learnr</code> R environment. Remember to make sure it is loaded</p>
<div class="tutorial-exercise" data-label="ex1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>library(&quot;MatchIt&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>The <code>MatchIt</code> package provides an example dataset named <code>lalonde</code>, containing a subset of data on The National Support Work Demonstration. This was a program based in the USA which aimed to support low-skilled workers to (re)enter the workforce. The dataset includes information on treated and untreated individuals, a range of background characteristics (including earnings before the intervention), and an outcome: earnings two years after the intervention.</p>
<p>More information on this dataset can be found in the original paper <a href="https://www.jstor.org/stable/1806062?seq=1#metadata_info_tab_contents">LaLonde (1986) Evaluating the Econometric Evaluations of Training Programs with Experimental Data</a></p>
<hr />
<p>Take some time to explore the data below, answering the following questions:</p>
<ol style="list-style-type: decimal">
<li>How many observations are there?<br />
</li>
<li>How many treated and untreated individuals are there? (the variable <strong>treat</strong> is the treatment indicator)</li>
<li>What background characteristics are available?</li>
<li>Are there any obvious differences between treated and untreated individuals?</li>
<li>How does the outcome differ between treated and untreated individuals? (the variable <strong>re78</strong> is the outcome—earnings two years after the program)</li>
</ol>
<div class="tutorial-exercise" data-label="ex2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="30">
<pre class="text"><code>str(lalonde)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
</div>
<div id="section-pause-and-think-5" class="section level3">
<h3>Pause and think</h3>
<div class="think">
<h3 id="section-what-can-we-say-about-the-data">What can we say about the data?</h3>
<p>There are some striking differences between the demographic characteristics of the treated and untreated groups. What are the implications when trying to evaluate the effectiveness of the program? <strong>Could you draw a DAG to represent your assumptions about the underlying causal structure</strong> relevant to the causal question of treatment participation on earnings?</p>
<p>(Keep in mind the cultural context—USA in the mid 1970s)</p>
</div>
</div>
</div>
<div id="section-identifiability-assumptions" class="section level2" data-progressive="TRUE">
<h2>Identifiability assumptions</h2>
<p>In order to make causal claims from observational data we must make some assumptions about the data, particularly with respect to the treatment or ‘action’ <span class="math inline">\(A\)</span>, the outcome <span class="math inline">\(Y\)</span> and any relevant pretreatment variables <span class="math inline">\(L\)</span>.</p>
<p>The three identifiability assumptions are:<br />
1. Positivity<br />
2. Exchangeability<br />
3. Consistency</p>
<p><img src="https://youtu.be/rgXD4MnPDgc" /></p>
<div id="section-positivity" class="section level3">
<h3>Positivity</h3>
<p>The assumption of positivity states that the conditional probability of receiving every possible treatment value must be positive, i.e. <span class="math inline">\(\gt0\)</span>.</p>
What this means is that there can not exist a category <span class="math inline">\(l\)</span> of a confounder <span class="math inline">\(L\)</span> where the probability of receiving the treatment is zero. Mathematically, we can write <span class="math display">\[
Pr(A=a|L=l)&gt;0 \; \text{for all treatments} \; a \; \text{and for all categories} \; l \epsilon L  
\]</span>
<div class="think">
<p>In simple terms, positivity means that it has to have been possible for every type of person to get the treatment.</p>
<h3 id="section-pause-and-think-6">Pause and think</h3>
<ol style="list-style-type: decimal">
<li><p>An implication of the positivity assumption is that there can’t be a treatment <span class="math inline">\(A\)</span> and a category <span class="math inline">\(l \epsilon L\)</span> where <span class="math inline">\(Pr(A=a|L=l)=1\)</span>. <strong>Why?</strong></p></li>
<li><p>What would be the implication if children of young mothers (<span class="math inline">\(\le19\)</span> years) were always entered into the Helping Hands program?</p></li>
</ol>
</div>
</div>
<div id="section-points-to-consider" class="section level3">
<h3>Points to consider</h3>
<ol style="list-style-type: decimal">
<li><p>To see why this is the case it is easiest to think in terms of a dichotomous treatment (0 or 1). If <span class="math inline">\(Pr(A=1|l)=1\)</span> then <span class="math inline">\(Pr(A=0|l)=0\)</span>, and positivity does not hold.</p></li>
<li><p>If children of young mothers were always entered into the Helping Hands program then <span class="math inline">\(Pr(A=1|age\le19)=1\)</span> and <span class="math inline">\(Pr(A=0|age\le19)=0\)</span>. Positivity does not hold. In simple terms, this is a problem because we can’t estimate the effect of the program in the whole population because there is no comparison for children of young mothers.</p></li>
</ol>
<hr />
</div>
<div id="section-exchangeability" class="section level3">
<h3>Exchangeability</h3>
<p>Exchangeability means that the conditional probability of receiving the treatment depends only on the measured covariates. In other words, treatment assignment can’t be related to the outcome <span class="math inline">\(Y\)</span>, either directly, or indirectly through an unobserved confounder.</p>
<p>In a randomised controlled trial, exchangeability is achieved through the random assignment of individuals to treatment groups. Given a sufficiently large trial, this process balances the background characteristics of the treated and untreated groups. Because these characteristics are balanced it doesn’t matter which group actually gets the treatment in an experimental design, i.e. the treatment groups are <em><em>exchangeable</em></em> and hence the term exchangeability.</p>
<p>Mathematically, we can express this relationship as <span class="math display">\[
\tilde{p}(L|A=0)=\tilde{p}(L|A=1)
\]</span> where <span class="math inline">\(\tilde{p}(.)\)</span> denotes the observed empirical density of the data.</p>
<p>In simple terms, exchangeability means that the treated and untreated groups need to have the same background characteristics.</p>
<hr />
<p>Exchangeability is much trickier when dealing with observational data. As discussed previously, when treatments aren’t randomly assigned there may be self-selection or other mechanisms that result in treated and untreated groups being different <em>in ways that relate to the outcome being measured</em>. The second half of this tutorial focusses on pre-processing techniques which can be applied to observational datasets to help avoid this situation and achieve the necessary balance.</p>
<p>We can never know for sure whether the assumption of exchangeability holds—there is no formal test. In practice, we must justify why we believe that departures from the assumption are not too severe, i.e. that we are close enough. For exchangeabilty to hold, all relevant pretreatment variables should be present in <span class="math inline">\(L\)</span>. This requires:</p>
<ul>
<li>Domain knowledge<br />
</li>
<li>A theoretical model<br />
</li>
<li>A well-thought out research design</li>
</ul>
<p><strong>Domain knowledge</strong> is needed to understand what factors are important for the causal question at hand, i.e. those that relate to treatment status and to the outcome of interest.</p>
<p><strong>A theoretical model</strong> is important to clarify what the researcher considers important and to distinguish from other variables that might be associated with the outcome but are not confounders. This is where Directed Acyclic Graphs (DAGs) are extremely useful as a tool to formalise these assumptions.</p>
<p><strong>A well-thought out research design</strong> is essential to make sure that the relevant factors, or proxies for them, are available. For example, we can’t control for a potential confounder such as maternal age if it hasn’t been recorded or linked from another source.</p>
</div>
<div id="section-consistency" class="section level3">
<h3>Consistency</h3>
<p>Consistency assumes that there is a <strong>single well-defined version of the treatment</strong>. It is also referred to as the no-multiple-versions-of-treatment assumption. So for example, we can not estimate the causal effect of participation in the helping hands program if some families only receive parenting classes while other families only receive home visits - this would imply two different types of treatment.</p>
<p>Of course, there is some wiggle-room here: even in a gold-standard intervention study some variation in treatment is unavoidable for practical reasons. In the example of Helping Hands, the same parenting class might be delivered by different instructors in different parts of the state. It is up to the researcher to decide what degree of variability in the treatment is permissable.</p>
<p>Lack of consistency is problematic because it</p>
<ul>
<li>Makes it difficult to assess exchangeability and positivity<br />
</li>
<li>Makes it unclear what the practical policy intervention should be</li>
</ul>
<div class="aside">
<h3 id="section-does-obesity-shorten-life">Does obesity shorten life?</h3>
<p>In a short article discussing the importance of consistency, <a href="https://www.nature.com/articles/ijo200882">Hernán and Taubman (2008)</a> pose the question <em>Does obesity shorten life?</em></p>
<p>Obesity is usually defined as BMI <span class="math inline">\(\ge\)</span> 30. In answering this question, we can consider the alternative to the “treatment” of obesity to be “not obsese” (BMI <span class="math inline">\(\lt\)</span> 30). However, the author’s argue that obesity is not a well-defined treatment, because there are multiple ways to achieve the alternative to the implicit treatment of obesity, e.g. </p>
<ul>
<li>Diet<br />
</li>
<li>Exercise<br />
</li>
<li>Surgery</li>
</ul>
<p>Thus, comparing obese and non-obese individuals in an observational study translates to a poorly-defined causal question: the implicit intervention is unclear because it is unknown what “treatment” obese individuals received to become obese.</p>
<p>A helpful thought experiment when estimating causal effects from observational data is to ask what hypothetical RCT you are emulating with your analysis (no matter how unethical or impractical that RCT might be). In the example of obesity and mortality, this would force us to ask <em>what is the treatment?</em> We would then need to consider how would we operationalise the “treatment” of obesity, leading us to more well-defined causal questions, i.e. the effect of diet, the effect of exercise, the effect of surgery etc.</p>
</div>
</div>
</div>
<div id="section-matching" class="section level2" data-progressive="TRUE">
<h2>Matching</h2>
<div id="section-overview-1" class="section level3">
<h3>Overview</h3>
<p>Matching is a preprocessing step which aims to balance the pre-treatment variables <span class="math inline">\(L\)</span> between the treated and untreated groups. This balance is achieved by dropping, duplicating, or weighting observations. The aim is to improve the assumption of exchangeability (which is achieved through randomisation in the case of a randomised control trial). Matching strengthens our ability to say that associations observed in the data are causal.</p>
<p>The key advantage of matching is that <strong>analyses of matched data reduce the dependency on model assumptions</strong>, in particular, parametric assumptions regarding the relationship between control variables and the outcome. This is important because equally valid statistical models can exhibit high degrees of model dependency, i.e. an estimated treatment effect can vary depending on the parametric form of the model chosen by the researcher.</p>
<p>A simple and intuitive form of matching is <strong>1:1 exact matching</strong>:</p>
<ul>
<li>Each treated unit is matched to a single control unit within the observational dataset<br />
</li>
<li>The observed confounders are matched exactly<br />
</li>
<li>e.g. each treated child <span class="math inline">\(i\)</span> with covariates <span class="math inline">\(L_{i}=(l_{1},l_{2},l_{3})\)</span> is matched to an untreated child <span class="math inline">\(j\)</span> with the same covariate vector <span class="math inline">\(L_{j}=(l_{1},l_{2},l_{3})\)</span>.</li>
</ul>
<div class="think">
<h3 id="section-pause-and-think-7">Pause and think</h3>
<p>What are the potential <strong>disadvantages</strong> of, and <strong>barriers</strong> to, 1:1 exact matching?</p>
</div>
</div>
<div id="section-reflection-points" class="section level3">
<h3>Reflection points</h3>
<ul>
<li>Usually there are fewer treated than untreated units, so 1:1 matching may discard a lot of records;<br />
</li>
<li>It may not be possible to get exact matches, especially if there are many covariates and/or limited potential controls</li>
</ul>
</div>
<div id="section-matching-workflow" class="section level3">
<h3>Matching workflow</h3>
<p>Analysing observational data using matching is a multi-stage process. The first stage—matching—is a <em>pre-processing</em> step.</p>
<p>The task of matching can be iterative: the analyst can, and should, try different matching approaches in order to optimise the balance in <span class="math inline">\(L\)</span> variables between the treated and untreated groups.</p>
<p>In the final stage, the analysis of substantive interest is performed using the matched data. This multi-stage, iterative workflow is depicted below.</p>
<div class="figure">
<img src="images/matching_workflow.png" alt="" />
<p class="caption">Workflow when matching</p>
</div>
<div id="section-analysing-matched-data" class="section level4">
<h4>Analysing matched data</h4>
<p>The analysis of the matched data could be as simple as comparing the difference in means for the outcome of interest in the treated and untreated groups. However, such a simple analysis will only be appropriate in the case of a 1:1 exact matching.</p>
<p>A better approach is to model the outcome of interest using an appropriate parametric model, including the <span class="math inline">\(L\)</span> covariates as controls (with appropriate functional forms e.g. quadratic terms etc). Using the confounding <span class="math inline">\(L\)</span> variables in both the matching and analysis stages makes the analysis <strong>doubly robust</strong>. This means that inferences will be valid if either (i) the matching stage or (ii) the parametric model is correct.</p>
</div>
</div>
</div>
<div id="section-matching-methods" class="section level2" data-progressive="TRUE">
<h2>Matching methods</h2>
<p><img src="https://youtu.be/bOA954e4HcU" /></p>
<div id="section-overview-2" class="section level3">
<h3>Overview</h3>
<p>In many practical situations, exact matching is not possible. For example:</p>
<ul>
<li>There are too many covariates to match on all variables at the same time<br />
</li>
<li>There are too few observations to find an exact match for each treated individual</li>
</ul>
<p>The alternative matching methods covered in this chapter can be grouped into two classes:</p>
<ol style="list-style-type: decimal">
<li>Coarsened Exact Matching</li>
<li>Distance-based Matching</li>
</ol>
</div>
<div id="section-coarsened-exact-matching" class="section level3">
<h3>Coarsened Exact Matching</h3>
<p>With Coarsened Exact Matching (CEM), we temporarily coarsen our matching variables and match using the coarsened versions. Coarsening means that we recode our variables to have wider bands, making it easier to find a match. For example, age measured in years might be coarsened to age measured in 10-year age bands; the logic being that it is easier to find a match for someone aged 30-39 than to find a match for someone who is 34 exactly.</p>
<p>Coarsened bands needn’t be equally spaced if there are more meaningful groupings available. For example, years in education could be coarsened to Primary (1-8), High School (9-12), Undergraduate (13-15) or Postgraduate (&gt;15). Similarly, BMI measured in <span class="math inline">\(kg/m^2\)</span> could be coarsened to the standard categories: Underweight (&lt; 18.5); Normal (18.5 - 24.9); Overweight (25.0 - 25.99); and Obese (<span class="math inline">\(\ge\)</span> 30).</p>
<p>The coarsened variables are only used for matching purposes; once the treatement and control groups have been balanced the analysis can proceed using the variables at the original scale of measurement.</p>
<p>In more detail, the steps for CEM are as follows:</p>
<ol style="list-style-type: decimal">
<li>The <span class="math inline">\(L\)</span> variables, on which the matches are based, are grouped, or <em>coarsened</em>. For example age measured in years might be coarsened to five-year age groups. Years of schooling might be grouped into high school, graduate and postgraduate.</li>
<li>Group individuals into strata based on the coarsened data. For example, if the matching variables are sex, age and education, a single stratum might comprise males aged 30-39 with high school education.</li>
<li>Drop the records in any strata that do not include at least one treated and one control unit. For example if there were no treated individuals who were males aged 20-29 years with a PhD then this stratum would be excluded.</li>
<li>The analysis proceeds in the matched data using the original coarsened variables. For the analysis model, control units in each stratum are weighted to equal the number of treated units in that stratum.</li>
</ol>
</div>
<div id="section-distance-based-matching" class="section level3">
<h3>Distance-based Matching</h3>
<p>Distance-based matching relies on some quantitative measure of the similarity/dissimilarity between observed individuals. Two individuals <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> are candidates for matching if the distance between them is suitably small, i.e. if <span class="math inline">\(D(i,j) \lt \delta\)</span>. The advantage of distance-based measures is that they reduce a large set of variables into a single univariate metric.</p>
<ul>
<li>The value <span class="math inline">\(\delta\)</span>, which determines eligible matches, is chosen by the analyst. This parameter is often referred to as the <em>calipers</em>.<br />
</li>
<li>Matches can be made at different ratios of treated to control, e.g. 1:1, 1:2 etc</li>
</ul>
<p><img src="https://youtu.be/q2RE86gZ2Yg" /></p>
<p>Two distance metrics commonly used in practice are:</p>
<ol style="list-style-type: decimal">
<li>The Mahalanobis distance<br />
</li>
<li>The propensity score</li>
</ol>
</div>
<div id="section-the-mahalanobis-distance" class="section level3">
<h3>The Mahalanobis distance</h3>
<p><img src="https://youtu.be/ABqX6h6I9d4" /></p>
<p>The Mahalanobis distance measures the average distance between two individuals <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> based on their multivariate vectors <span class="math inline">\(X_{i}\)</span> and <span class="math inline">\(X_{j}\)</span> as</p>
<p><span class="math display">\[
d(X_{i}, X_{j})  = \sqrt{(X_{i} - X_{j})^{T}S^{-1}(X_{i} - X_{j})}
\]</span> where <span class="math inline">\(S\)</span> is the sample variance-covariance matrix of <span class="math inline">\(X\)</span>.</p>
<p>So here, <span class="math inline">\(X_{i}\)</span> would be a vector of responses for person <span class="math inline">\(i\)</span> - say age, income, years of education etc. <span class="math inline">\(X_{j}\)</span> would be the same set of responses for person <span class="math inline">\(j\)</span>, and <span class="math inline">\(X_{i} - X_{j}\)</span> is the vector of differences between person <span class="math inline">\(i\)</span> and person <span class="math inline">\(j\)</span> on each variable. The superscript <span class="math inline">\(T\)</span> indicates the matrix operation <em>transpose</em>.</p>
<p>While <span class="math inline">\(X_{i}\)</span> and <span class="math inline">\(X_{j}\)</span> refer to data for two individuals (or rows in your dataset), <span class="math inline">\(S\)</span> is the variance-covariance matrix estimated from <em>all</em> of the data, exactly as returned by R if you called the <code>cov()</code> function on your dataframe of observations.</p>
<p>The Mahalanobis distance has two useful properties:</p>
<ol style="list-style-type: lower-roman">
<li><p>It <strong>standardises</strong> the variables recorded in <span class="math inline">\(X\)</span>. This means that the units used in your data have no impact on the distance - it doesn’t matter if weight is recorded in pounds or kilograms or if income is recorded in dollars or ’000s of dollars, the resulting distances will be the same.</p></li>
<li><p>It takes into account the <strong>covariance</strong> structure in the data when calculating distance. To see what this means, consider the ponts <strong>a</strong> and <strong>b</strong> on the scatterplot of education versus salary below.</p></li>
</ol>
<p><img src="matching_files/figure-html/unnamed-chunk-2-1.png" width="624" /></p>
<p>The two points <strong>a</strong> and <strong>b</strong> are the same Euclidean distance from the centroid of the data (i.e. the red and green lines are the same length). But intuitively we can see that the point <strong>a</strong> has values of education and salary that correspond to the overall relationship between a and b, whereas point <strong>b</strong> does not fit so closely with the observed data. The Mahalanobis distance reflects this intuition and returns a closer distance for <strong>a</strong> to the centroid of the data compared to the distance from <strong>b</strong> to the centroid of the data.</p>
<p>An intuitive way to understand how this works is to consider the variance-covariance term <span class="math inline">\(S\)</span> in the formula for the Mahalanobis distance. If two variables are closely related, their covariance will be high. Dividing by a high number. Below is the result of <span class="math inline">\((X_{i} - X_{j})^{T}S^{-1}\)</span>. Note that</p>
<ul>
<li>The data re now centred on (0, 0)</li>
<li>The magnitude of the relationship is the same (although the direction has flipped)</li>
<li>Point <em>a</em> is much closet to the centroid of the data compared to point <strong>b</strong></li>
</ul>
<p><img src="matching_files/figure-html/unnamed-chunk-4-1.png" width="624" /></p>
<p>Another intuitive way to think about the Mahalanobis distance is to recognise the parallels between the formula above and the familiar standardised difference in means <span class="math inline">\(d=\frac{\bar{x_{i}}-\bar{x_{j}}}{\sigma}\)</span> (i.e. difference in means divided by the standard deviation).</p>
<div class="calipers">
<h3 id="section-aside-1">Aside</h3>
<p>The Mahalanobis distance measure was proposed by the Indian scientist and statistician Prasanta Chandra Mahalanobis (1893-1972) in the 1920s. The measure was used to compare individuals from Bengal castes based on multivariate anthropometric data, including skull measurements.</p>
<p>Maybe that’s why the term <em>calipers</em> is used?</p>
</div>
</div>
<div id="section-the-propensity-score" class="section level3">
<h3>The propensity score</h3>
<p><img src="https://youtu.be/8dRpXafdcF4" /></p>
<p>The propensity score refers to the probability of receiving the treatment <span class="math inline">\(A\)</span>. In some settings, such as RCTs, the propensity score might be known and chosen in advance (e.g. people in group A receive the treatment with probability <span class="math inline">\(p=0.5\)</span>). With observational data, the true propensity score is unknown and must be estimated from the available data. In practice, this is typically done using a logistic regression of the dichotomous treatment indicator <span class="math inline">\(A\)</span> on the observed confounders <span class="math inline">\(L\)</span>. This gives a model of the form</p>
<p><span class="math display">\[
\text{log} \left(\frac{1-\pi_{i}}{\pi_{i} }\right) = \beta X_{i}  
\]</span> where <span class="math inline">\(\pi_{i} = \text{Pr}(A_{i}=1)\)</span>. Given the model parameter estimates <span class="math inline">\(\hat{\beta}\)</span>, the estimate of the propensity score <span class="math inline">\(\hat{\pi_{i}}\)</span> is <span class="math display">\[
\hat{\pi_{i}} = \left(e^{-\hat{\beta} X_{i}} + 1\right)^{-1}
\]</span></p>
<p>The distance-based on the propensity score for two individuals is then simply <span class="math inline">\(\pi_{i}-\pi_{j}\)</span>. It is also possible to base the differences on the log scale, i.e. <span class="math inline">\(\beta X_{i}-\beta X_{j}\)</span></p>
<p>While it is commonplace to use a logistic regression to estimate the propensity score from observed data, any suitable model can be used, including <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0231500">machine learning algorithms</a>.</p>
<hr />
</div>
<div id="section-utilising-the-propensity-score" class="section level3">
<h3>Utilising the propensity score</h3>
<p>Matching is not the only way to utilise propensity scores to aid causal inference. Other applications include:</p>
<p><strong>Stratification</strong><br />
Under stratification, the full sample is divided into a small number of strata (e.g. 5-10) based on the propensity score. The causal effect is then estimated seperately within each strata.</p>
<p><strong>Weighting</strong><br />
Under weighting, the full sample is reweighted to balance the propensity score between the treated and untreated subgroups.</p>
</div>
<div id="section-criticism-of-propensity-score-matching" class="section level3">
<h3>Criticism of propensity score matching</h3>
<p>Propensity score matching is a very popular approach in practice, but has been subject to criticism, for example King and Nielson (2016) <a href="https://gking.harvard.edu/files/gking/files/psnot.pdf">Why Propensity Scores should not be used for matching</a>. See the prereading linked at the start of this tutorial for more on this topic.</p>
<p>These criticisms stem from the fact that, once balance is achieved on the <em>global</em> propensity score, the matching process ignores <em>local</em> information on the individual covariates in <span class="math inline">\(L\)</span>. Thus, any pruning that takes place is random. Consequently, matching based on the propensity score approximates a completely randomised experiment, whereas other methods approximate a more efficient fully blocked experiment.</p>
</div>
<div id="section-discussion" class="section level3">
<h3>Discussion</h3>
<div class="family">
<h3 id="section-consider-1">Consider…</h3>
<p>…the following (very) simplified example:</p>
<p>Using data on child and family background, you could use a logistic regression to estimate the probability of being involved in the Helping Hands program, conditional on child and family characteristics.</p>
<p>Based on the estimated model parameters, you find the following probabilities for Armin (who ultimately did partake in the program) and Nina (who did not partake in the program). <span class="math display">\[
\begin{aligned}
\hat{\pi}_{Armin} &amp; = 0.715 &amp; \\
\hat{\pi}_{Nina} &amp; = 0.725 &amp;
\end{aligned}
\]</span></p>
<p>Based on these estimated propensity scores, matching Armin with Nina seems like good candidate match. Nina, who was untreated, can supply the counterfactual for Armin, who was treated.</p>
<p>Suppose you dig deeper on the children’s background characteristics (their <span class="math inline">\(L\)</span> values). We find the following:</p>
<p><strong>Armin</strong></p>
<ul>
<li>Maternal age = 17<br />
</li>
<li>Parental income = medium</li>
</ul>
<p><strong>Nina</strong></p>
<ul>
<li>Maternal age = 32<br />
</li>
<li>Parental income = low</li>
</ul>
<p>Clearly the two children have different background characteristics for the covariates <em>Maternal age</em> and <em>Parental income</em>.</p>
<p>Checking the estimated model coefficients, you confirm your suspicions: Armin has a relatively high propensity score because he was born to a young mum; Nina has a relatively high propensity score because she is from a low-income family.</p>
<p>Are the two children really a good match?</p>
</div>
</div>
</div>
<div id="section-practical-2" class="section level2">
<h2>Practical 2</h2>
<div id="section-matching-using-matchit" class="section level3">
<h3>Matching using <code>MatchIt</code></h3>
<p>The <code>matchit</code> function contained in the <code>MatchIt</code> package implements a wide variety of matching procedures.</p>
<p>The basic syntax (noting many more options are available) is as follows:</p>
<pre class="r"><code>matchit(formula, data, method = &quot;nearest&quot;, distance = &quot;logit&quot;, ratio=1, discard = &quot;none&quot;)</code></pre>
<p><strong>formula</strong> specifies the <span class="math inline">\(A\)</span> and <span class="math inline">\(L\)</span> variables, and takes the usual R formula syntax, e.g. <code>A ~ l1 + l2 + ... + ln</code><br />
<strong>data</strong> refers to the dataset containing the treatment indicator <span class="math inline">\(A\)</span> and the pre-treatment covariates <span class="math inline">\(L\)</span><br />
<strong>method</strong> refers to the matching method. The default is ‘nearest’ i.e. nearest neighbour matching<br />
<strong>distance</strong> refers to the distance metric. The default ‘logit’ bases the distance on the propensity score estimated using logistic regression<br />
<strong>ratio</strong> refers to the number of untreated units matched to each treated unit. The default is 1<br />
<strong>discard</strong> allows the user to prune observations outside the region of common support before matching begins</p>
<hr />
<p>The example below matches treated and untreated units based on the variables <em>race</em> (Black, Hispanic or White) and <em>re74</em> (income in 1974). The matching method is 1:1 nearest neghbour matching, based on the propensity score.</p>
<pre class="r"><code>match1 &lt;- matchit(treat ~ race + re74, data=lalonde,
                  method = &quot;nearest&quot;, distance = &quot;logit&quot;, ratio=1, discard = &quot;none&quot;)

match1</code></pre>
<pre><code>## A matchit object
##  - method: 1:1 nearest neighbor matching without replacement
##  - distance: Propensity score
##              - estimated with logistic regression
##  - number of obs.: 614 (original), 370 (matched)
##  - target estimand: ATT
##  - covariates: race, re74</code></pre>
<ul>
<li>Note there is one matched control unit (n=185) for each treated unit (n=185)<br />
</li>
<li>244 units are unmatched</li>
</ul>
</div>
<div id="section-try-it-yourself" class="section level3">
<h3>Try it yourself</h3>
<p>Adapt the above code to implement 2:1 nearest neighbour matching based on the propensity score</p>
<div class="tutorial-exercise" data-label="ex5" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>match2 &lt;- matchit( )</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<ul>
<li>How many matched and control units are there?</li>
</ul>
<hr />
<p>Adapt the above code to implement exact matching based on the variable <strong>age</strong>. (Note that exact matching in <code>MatchIt</code> includes <em>all</em> valid matches, so it is not possible to choose a ratio)</p>
<div class="tutorial-exercise" data-label="ex6" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#match3 &lt;- matchit( )</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
</div>
</div>
<div id="section-assessing-balance" class="section level2" data-progressive="TRUE">
<h2>Assessing balance</h2>
<p>Because exact matching is rarely possible in practice, it is expected that there will be some imbalance in the <span class="math inline">\(L\)</span> covariates comparing the matched treated and untreated groups. The analyst must assess the degree of balance achieved by different matching approaches, and attempt to optimise the balance.</p>
<p>Ideally, we would like to ensure that the <strong>multivariate</strong> distribution of <span class="math inline">\(L\)</span> is the same in the treated and untreated groups. Because <span class="math inline">\(L\)</span> typically contains many individual variables, this is often infeasible in practice. A practical alternative is to compare the <span class="math inline">\(L\)</span> variables at lower dimensions, i.e. univariate or bivariate comparisons between the treated and untreated groups.</p>
<p>Balance is solely a property of the observed data, not some broader population. Therefore, hypothesis testing, or statistical significance tests are neither necessary nor relevant (Ho et al 2007).</p>
<div id="section-common-support" class="section level3">
<h3>Common Support</h3>
<p>Part of achieving balance is ensuring that the <span class="math inline">\(L\)</span> covariates in the matched treated and untreated groups have an overlapping distribution. This region of the data is referred to as <strong>common support</strong>. Including observations outside the common support is problematic as it requires extrapolation, and therefore model dependence. Common support is achieved by pruning observations where the <span class="math inline">\(L\)</span> covariates do not overlap. Common support should be assessed for individual variables. In practice, common support is often assessed solely on the propensity score, which contains information on all <span class="math inline">\(L\)</span> variables. This may not be a good idea, however, for the reasons discussed previously.</p>
<p>The figure below presents a hypothetical example comparing the distribution of a continuous pretreatment variable for treated and untreated groups.</p>
<ul>
<li>The area of common support is 20-35<br />
</li>
<li>Observations &lt;20 and &gt;35 should be pruned<br />
</li>
<li>The matching process should balance the distribution within the area of common support, i.e. by weighting up lower values (20-25) and weighting down heigher values (30-35) in the treated group.</li>
</ul>
<div class="figure">
<img src="images/common_support.png" alt="" />
<p class="caption">Illustration of common support</p>
</div>
<div class="family">
<h3 id="section-discussion-1">Discussion</h3>
<ul>
<li>Can you give a hypothetical example of how common support would be broken in an analsis of the effectiveness of the Helping Hands program?</li>
<li>Draw a picture depicting zero common support for a continuous variable.<br />
</li>
<li>What identifiability assumption has this broken?</li>
</ul>
</div>
</div>
<div id="section-bias-variance-trade-off" class="section level3">
<h3>Bias-variance trade-off</h3>
<p>As with many statistical techniques, there is a trade-off between bias and variance in the task of balancing treated and untreated groups. Pruning observations:</p>
<ul>
<li>Increases balance<br />
</li>
<li>Reduces sample size<br />
</li>
<li>Bias <span class="math inline">\(\downarrow\)</span> Variance <span class="math inline">\(\uparrow\)</span></li>
</ul>
</div>
</div>
<div id="section-practical-3" class="section level2" data-progressive="TRUE">
<h2>Practical 3</h2>
<div id="section-assessing-balance-1" class="section level3">
<h3>Assessing balance</h3>
<p>The purpose of matching data prior to analysis is to balance the <span class="math inline">\(L\)</span> covariates between treated and control groups. Greater balance makes the assumption of exchangeability more plausible, which strengthens any causal inferences made from observational data. An important part of the process is therefore assessing how well the matching approach has done at balancing the covariates. <code>MatchIt</code> includes several diagnostics to help assess balance, including numerical summaries and visualisations.</p>
<div id="section-remember" class="section level4">
<h4>Remember</h4>
<ul>
<li>It is ok to try multiple matching techniques to achieve balance<br />
</li>
<li>The outcome <span class="math inline">\(Y\)</span> should never be used when matching</li>
</ul>
</div>
</div>
<div id="section-numerical-summaries" class="section level3">
<h3>Numerical summaries</h3>
<p>Calling the <code>summary()</code> function on the output of <code>matchit</code> returns a comparison of the means of the matched variables in treated and untreated gorups, for the raw data and for the matched data. An example is shown below:</p>
<pre class="r"><code>match4 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;nearest&quot;)

summary(match4)</code></pre>
<pre><code>## 
## Call:
## matchit(formula = treat ~ age + educ + race + married + nodegree + 
##     re74 + re75, data = lalonde, method = &quot;nearest&quot;)
## 
## Summary of Balance for All Data:
##            Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance          0.5774        0.1822          1.7941     0.9211    0.3774
## age              25.8162       28.0303         -0.3094     0.4400    0.0813
## educ             10.3459       10.2354          0.0550     0.4959    0.0347
## raceblack         0.8432        0.2028          1.7615          .    0.6404
## racehispan        0.0595        0.1422         -0.3498          .    0.0827
## racewhite         0.0973        0.6550         -1.8819          .    0.5577
## married           0.1892        0.5128         -0.8263          .    0.3236
## nodegree          0.7081        0.5967          0.2450          .    0.1114
## re74           2095.5737     5619.2365         -0.7211     0.5181    0.2248
## re75           1532.0553     2466.4844         -0.2903     0.9563    0.1342
##            eCDF Max
## distance     0.6444
## age          0.1577
## educ         0.1114
## raceblack    0.6404
## racehispan   0.0827
## racewhite    0.5577
## married      0.3236
## nodegree     0.1114
## re74         0.4470
## re75         0.2876
## 
## 
## Summary of Balance for Matched Data:
##            Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance          0.5774        0.3629          0.9739     0.7566    0.1321
## age              25.8162       25.3027          0.0718     0.4568    0.0847
## educ             10.3459       10.6054         -0.1290     0.5721    0.0239
## raceblack         0.8432        0.4703          1.0259          .    0.3730
## racehispan        0.0595        0.2162         -0.6629          .    0.1568
## racewhite         0.0973        0.3135         -0.7296          .    0.2162
## married           0.1892        0.2108         -0.0552          .    0.0216
## nodegree          0.7081        0.6378          0.1546          .    0.0703
## re74           2095.5737     2342.1076         -0.0505     1.3289    0.0469
## re75           1532.0553     1614.7451         -0.0257     1.4956    0.0452
##            eCDF Max Std. Pair Dist.
## distance     0.4216          0.9740
## age          0.2541          1.3938
## educ         0.0757          1.2474
## raceblack    0.3730          1.0259
## racehispan   0.1568          1.0743
## racewhite    0.2162          0.8390
## married      0.0216          0.8281
## nodegree     0.0703          1.0106
## re74         0.2757          0.7965
## re75         0.2054          0.7381
## 
## Percent Balance Improvement:
##            Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max
## distance              45.7     -239.6      65.0     34.6
## age                   76.8        4.6      -4.2    -61.1
## educ                -134.8       20.4      31.2     32.1
## raceblack             41.8          .      41.8     41.8
## racehispan           -89.5          .     -89.5    -89.5
## racewhite             61.2          .      61.2     61.2
## married               93.3          .      93.3     93.3
## nodegree              36.9          .      36.9     36.9
## re74                  93.0       56.8      79.1     38.3
## re75                  91.2     -800.7      66.3     28.6
## 
## Sample Sizes:
##           Control Treated
## All           429     185
## Matched       185     185
## Unmatched     244       0
## Discarded       0       0</code></pre>
<p>Examining the above output we can see that the matching step has improved the balance of <span class="math inline">\(L\)</span> variables in the treated and untreated groups. For example:</p>
<ul>
<li>In the raw data, treated individuals were younger on average compared to untreated individuals (25.8 years versus 28.0 years)<br />
</li>
<li>In the matched data, the treated and untreated individuals had a similar age on average (25.8 years versus 25.3 years)</li>
</ul>
<p>The data still aren’t perfectly matched however. For example, in the matched data the proportion of Black individuals is still notably higher in the treated group (84%) than the untreated group (47%).</p>
</div>
<div id="section-graphical-summaries" class="section level3">
<h3>Graphical summaries</h3>
<p><code>MatchIt</code> provides three main graphical summaries:</p>
<ol style="list-style-type: decimal">
<li><strong>Jitter plot</strong> plots the distribution of the propensity scores in the treated and untreated groups<br />
</li>
<li><strong>Histogram</strong> plots histograms of the propensity score for the treated and untreated groups<br />
</li>
<li><strong>Q-Q plot</strong> plots quantile-quantile plots for the individual <span class="math inline">\(L\)</span> variables</li>
</ol>
<p>These diagnostic graphs are accessed by calling the <code>plot()</code> on the output of <code>matchit</code>, and specifying the appropriate type argument:</p>
<pre class="r"><code>plot(match4, type=&quot;jitter&quot;)
plot(match4, type=&quot;hist&quot;)
plot(match4, type=&quot;QQ&quot;)</code></pre>
</div>
<div id="section-jitter-plot" class="section level3">
<h3>Jitter plot</h3>
<p>Example code and output for the jitter plot graphical diagnostic are shown below.</p>
<pre class="r"><code>match4 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;nearest&quot;)

plot(match4, type=&quot;jitter&quot;)</code></pre>
<p><img src="matching_files/figure-html/ex9-1.png" width="624" /></p>
<pre><code>## [1] &quot;To identify the units, use first mouse button; to stop, use second.&quot;</code></pre>
<pre><code>## integer(0)</code></pre>
<ul>
<li>There is common support for the propensity score for the matched treated and control units between 0 and 0.8 (approx)</li>
</ul>
</div>
<div id="section-histogram" class="section level3">
<h3>Histogram</h3>
<p>Example code and output for the histogram graphical diagnostic are shown below.</p>
<pre class="r"><code>match4 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;nearest&quot;)

plot(match4, type=&quot;hist&quot;)</code></pre>
<p><img src="matching_files/figure-html/ex10-1.png" width="624" /></p>
<ul>
<li>The propensity score is more balanced in the matched data than in the raw data</li>
</ul>
</div>
<div id="section-quantile-quantile-q-q-plot" class="section level3">
<h3>Quantile-Quantile (Q-Q) plot</h3>
<p>Example code and output for the Q-Q graphical diagnostic are shown below.</p>
<pre class="r"><code>match4 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;nearest&quot;)

plot(match4, type=&quot;QQ&quot;)</code></pre>
<p><img src="matching_files/figure-html/ex11-1.png" width="624" /><img src="matching_files/figure-html/ex11-2.png" width="624" /><img src="matching_files/figure-html/ex11-3.png" width="624" /></p>
<ul>
<li>Q-Q plots plot the quantiles of the treated and untreated units in the raw data and the matched data<br />
</li>
<li>When variables are balanced the data points will lie on the 45 degree line (<span class="math inline">\(y=x\)</span>)</li>
</ul>
</div>
<div id="section-try-it-yourself-1" class="section level3">
<h3>Try it yourself</h3>
<p>Use the code blocks below to match the lalonde data on all available variables according to the following specifications:</p>
<ol style="list-style-type: decimal">
<li>Nearest neighbour propensity score matching (2:1 ratio)<br />
</li>
<li>Optimal matching based on the Mahalanobis distance (2:1 ratio)<br />
</li>
<li>Coarsened exact matching</li>
</ol>
<p>Examine the balance diagnostics. Which approach achieves the best balance?</p>
<div class="tutorial-exercise" data-label="ex12" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<pre class="text"><code># Nearest neighbour propensity score matching (2:1 ratio) 

match5 &lt;- matchit( )

summary(match5)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ex12-hint" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Nearest neighbour propensity score matching (2:1 ratio) 

match5 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;nearest&quot;, distance = &quot;logit&quot;, ratio = 2)

summary(match5)</code></pre>
</div>
<hr />
<div class="tutorial-exercise" data-label="ex13" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<pre class="text"><code># Optimal matching based on the Mahalanobis distance (2:1 ratio)

match6 &lt;- matchit( )

summary(match6)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ex13-hint" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Optimal matching based on the mahalanobis distance (2:1 ratio)

match6 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;optimal&quot;, distance = &quot;mahalanobis&quot;, ratio = 2)

summary(match6)</code></pre>
</div>
<hr />
<div class="tutorial-exercise" data-label="ex14" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<pre class="text"><code># Coarsened exact matching
# use method = &quot;cem&quot;

match7 &lt;- matchit( )

summary(match7)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ex14-hint" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Coarsened exact matching

match7 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;cem&quot;)

summary(match7)</code></pre>
</div>
</div>
</div>
<div id="section-practical-4" class="section level2" data-progressive="TRUE">
<h2>Practical 4</h2>
<div id="section-analysing-matched-data-1" class="section level3">
<h3>Analysing matched data</h3>
<p>Once the optimal balance in <span class="math inline">\(L\)</span> variables has been achieved, the final step is to compare the outcome(s) of interest for the matched treated and control groups. To do this we have to be able to access the matched data generated by <code>matchit</code>. This is done using the function <code>match.data</code>.</p>
<div class="tutorial-exercise-support" data-label="prac4setup" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Nearest neighbour propensity score matching (2:1 ratio) 
match5 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;nearest&quot;, distance = &quot;logit&quot;, ratio = 2)

# Optimal matching based on the Mahalanobis distance (2:1 ratio)
match6 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;optimal&quot;, distance = &quot;mahalanobis&quot;, ratio = 2)

# Coarsened exact matching (2:1 ratio)
match7 &lt;- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, data=lalonde, method = &quot;cem&quot;)</code></pre>
</div>
<p>For example, we can extract the matched data from the match #5, as follows.</p>
<div class="tutorial-exercise" data-label="ex15" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Save the matched data from matching attempt #5 
match5.data &lt;- match.data(match5)

head(match5.data)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"prac4setup","exercise.checker":"NULL"}</script>
</div>
<p>Note that there are two new variables in the matched dataset:</p>
<ul>
<li><strong>distance</strong> The distance metric—in this case the propensity score<br />
</li>
<li><strong>weights</strong> A set of weights which balances the matched treated and control units, where necessary. <code>MatchIt</code> weights the control units to match the treated units, thus estimates applying the weights return the Average Treatment Effect on the Treated (ATT). Unmatched units are given a weight of 0 (and do not appear in the file). All matched treated units are given a weight of 1. Each matched control unit is given a weight proportional to the number of treated units to which it was matched. The control weights add up to give the number of uniquely matched control units.</li>
</ul>
<hr />
<p>Once the data have been saved, we can use a simple OLS to gauge the effect of matching on the outcome of interest. Recall, the outcome is the variable <strong>re78</strong>: earnings (in US$) two years after the program.</p>
<p>Complete the code below to save the matched data from the matching approaches 5-7, and to compare the simple OLS regression <strong>re78 ~ treat</strong> in the raw data and in each matched dataset.</p>
<div class="tutorial-exercise" data-label="ex16" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="20">
<pre class="text"><code># Save the matched data 
match5.data &lt;- match.data(match5)
match6.data &lt;-
match7.data &lt;-

# Fit an ols model to the raw data and the alternative sets of matched data  
  
mod0 &lt;- lm(re78 ~ treat, data=lalonde)  
mod5 &lt;- lm(re78 ~ treat, data=match5.data, weight=weights)
mod6 &lt;- 
mod7 &lt;-  

summary(mod0)    
summary( )
summary( )
summary( )</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"prac4setup","exercise.checker":"NULL"}</script>
</div>
</div>
<div id="section-pause-and-think-8" class="section level3">
<h3>Pause and think</h3>
<div class="think">
<h3 id="section-what-are-the-estimates-telling-you">What are the estimates telling you?</h3>
<p>Before moving on, make sure you match the estimates in the model output to the parameters of interest. for each model, can you identify:</p>
<ul>
<li>The baseline estimate of earnings for non-participants?</li>
<li>The estimated effect on earnings for participants?</li>
</ul>
<p>Which estimates are more precise and why?</p>
</div>
</div>
<div id="section-interpretation" class="section level3">
<h3>Interpretation</h3>
<ul>
<li>In the model based on the raw data (<strong>mod0</strong>), the average annual earnings are $6984, and program participation <em>decreases</em> annual earnings by $635 on average.<br />
</li>
<li>In the models based on the matched data, the estimated effect of program participation is positive—a more intuitive result
<ul>
<li>$220 based on the nearest neighbour matching with the propensity score distance</li>
<li>$230 based on optimal matching with the Mahalanobis distance</li>
<li>$415 based on coarsened exact matching</li>
</ul></li>
</ul>
</div>
</div>
<div id="section-activities" class="section level2">
<h2>Activities</h2>
<div class="shiny">
<h3 id="section-activity-1.-model-dependency">Activity 1. Model dependency</h3>
<p>Play with the toy example illustrating how matching removes model dependency using this <a href="https://cbdrh.shinyapps.io/matching-model-dependency/">interactive Shiny app</a>. The app can also be launched by entering <code>hdat9700tutorials::run('matching-1')</code> at the console.</p>
<p>This app emulates the example discussed by Professor Gary King in this weeks pre-reading, check it out below:</p>
<p><a href="https://youtu.be/rBv39pK1iEs?t=199"><img src="images/prof-king-vid.png" style="width:25.0%" /></a></p>
<hr />
<h3 id="section-activity-2.-the-matchit-package">Activity 2. The MatchIt Package</h3>
<p>Explore some of the functionality of the MatchIt package using this <a href="https://cbdrh.shinyapps.io/matching-2">interactive Shiny app</a>. The app can also be launched by entering <code>hdat9700tutorials::run('matching-2')</code> at the console.</p>
</div>
</div>
<div id="section-summary" class="section level2">
<h2>Summary</h2>
<p>The key message from this chapter is that it is possible to identify estimates of causal effects from observational data, provided the three identifiability assumptions are met. Re call these three assumptions are</p>
<ol style="list-style-type: decimal">
<li>Positvity <em>it has to have been possible for every type of person to get the treatment</em></li>
<li>Exchangeability <em>the treated and untreated groups need to have the same background characteristics</em></li>
<li>Consistency <em>there is a single well-defined version of the treatment</em></li>
</ol>
<p>Matching is a pre-processing step which aims to construct a dataset where the treated and control individuals are balanced in terms of background variables. This helps to strengthen the assumption of <em>Exchangeability</em>.</p>
<p>Matching based on a <em>propensity score</em> allows many variables to be incorporated into the matching process. The ‘propensity’ refers to the propensity to be treated, and is typically estimated using logistic regression with the treatment indicator as the outcome.</p>
<p>Applying propensity scores can improve the assumption of <em>positivity</em> by encouraging the analysts to examine individuals for common support and trimming observations that don’t meet this criteria.</p>
<p>A <em>criticism</em> of propensity score matching is that balance is achieved on the <em>global</em> propensity score, but ignores <em>local</em> information on the individual covariates.</p>
</div>
<div id="section-references" class="section level2">
<h2>References</h2>
<p>“Matching as Nonparametric Preprocessing for Reducing Model Dependence in Parametric Causal Inference” by Daniel Ho, Kosuke Imai, Gary King and Elizabeth Stuart, Political Analysis (2007) 15:199–236 Available <a href="https://gking.harvard.edu/files/matchp.pdf">here</a>.</p>
<p>“MatchIt: Nonparametric Preprocessing for Parametric Causal Inference” by Daniel E. Ho, Kosuke Imai, Gary King and Elizabeth A. Stuart, Journal of Statistical Software (2011) 42(8), 1-28. Available <a href="https://r.iq.harvard.edu/docs/matchit/2.4-20/matchit.pdf">here</a></p>
<p>“Causal Inference” by Miguel A. Hernán, James M. Robins, Boca Raton: Chapman &amp; Hall/CRC (forthcoming) available <a href="https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1268/2018/08/hernanrobins_v1.10.36.pdf">here</a></p>
<p>“Data science is science’s second chance to get causal inference right. A classification of data science tasks” by Miguel A. Hernán John Hsu and Brian Healy (Preprint version) Available <a href="https://arxiv.org/ftp/arxiv/papers/1804/1804.10846.pdf">here</a></p>
<p>“Does obesity shorten life? The importance of well-defined interventions to answer causal questions” by MA Hernán amd SL Taubman, International Journal of Obesity (2008) volume 32, pages S8–S14 Available <a href="https://www.nature.com/articles/ijo200882">here</a></p>

<script type="application/shiny-prerendered" data-context="server-start">
library("learnr")
knitr::opts_chunk$set(echo = FALSE)

## required packages for examples - note that RMarkdown, learnr (and RStudio!) are also required.
library("MatchIt")
library("cem")
library("optmatch")
library("knitr")
library("kableExtra")
library("ggdag")
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = list(id = "au.edu.unsw.cbdrh.hdat9700.tutorials.matching"))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz1-1", question = structure("Helping Hands participation status for a child is a potential example of", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_89292b6",     option = "$Y_{a=1}$", value = "$Y_{a=1}$", label = structure("\\(Y_{a=1}\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_baf81b3",     option = "$A$", value = "$A$", label = structure("\\(A\\)", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_7b66190",     option = "$L$", value = "$L$", label = structure("\\(L\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz1-1-answer", question = "quiz1-1"), loading = structure("<strong>Loading:<\u002fstrong> \nHelping Hands participation status for a child is a potential example of\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 452727318.789182, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz1-2", question = structure("Development outcomes for a child who participated in Helping Hands is a potential example of", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_e4cbfa6",     option = "$Y_{a=1}$", value = "$Y_{a=1}$", label = structure("\\(Y_{a=1}\\)", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_cf9d862",     option = "$A$", value = "$A$", label = structure("\\(A\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_508cc5b",     option = "$L$", value = "$L$", label = structure("\\(L\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz1-2-answer", question = "quiz1-2"), loading = structure("<strong>Loading:<\u002fstrong> \nDevelopment outcomes for a child who participated in Helping Hands is a potential example of\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 962837294.551644, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz1-3", question = structure("A child&#39;s parents income is a potential example of", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_da71672",     option = "$Y_{a=1}$", value = "$Y_{a=1}$", label = structure("\\(Y_{a=1}\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_1129d3e",     option = "$A$", value = "$A$", label = structure("\\(A\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_10f9377",     option = "$L$", value = "$L$", label = structure("\\(L\\)", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz1-3-answer", question = "quiz1-3"), loading = structure("<strong>Loading:<\u002fstrong> \nA child&#39;s parents income is a potential example of\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1883895486.12274, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz2-1", question = structure("The causal effect on the additive scale is", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_ff8895f",     option = "1.0", value = "1.0", label = structure("1.0", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_40e597c",     option = "$0.67$", value = "$0.67$", label = structure("\\(0.67\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_c10c934",     option = "$1.5$", value = "$1.5$", label = structure("\\(1.5\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_c625c1",     option = "0.2", value = "0.2", label = structure("0.2", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz2-1-answer", question = "quiz2-1"), loading = structure("<strong>Loading:<\u002fstrong> \nThe causal effect on the additive scale is\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 100559200.453173, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz2-2", question = structure("The causal effect on the multiplicative scale is", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_dabaac",     option = "1.0", value = "1.0", label = structure("1.0", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ad77e8c",     option = "$0.67$", value = "$0.67$", label = structure("\\(0.67\\)", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_590199b",     option = "$1.5$", value = "$1.5$", label = structure("\\(1.5\\)", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_e46f859",     option = "0.2", value = "0.2", label = structure("0.2", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz2-2-answer", question = "quiz2-2"), loading = structure("<strong>Loading:<\u002fstrong> \nThe causal effect on the multiplicative scale is\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 2007359594.56525, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex1-code-editor`)), session)
output$`tutorial-exercise-ex1-output` <- renderUI({
  `tutorial-exercise-ex1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex2-code-editor`)), session)
output$`tutorial-exercise-ex2-output` <- renderUI({
  `tutorial-exercise-ex2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex5-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex5-code-editor`)), session)
output$`tutorial-exercise-ex5-output` <- renderUI({
  `tutorial-exercise-ex5-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex6-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex6-code-editor`)), session)
output$`tutorial-exercise-ex6-output` <- renderUI({
  `tutorial-exercise-ex6-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex12-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex12-code-editor`)), session)
output$`tutorial-exercise-ex12-output` <- renderUI({
  `tutorial-exercise-ex12-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex13-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex13-code-editor`)), session)
output$`tutorial-exercise-ex13-output` <- renderUI({
  `tutorial-exercise-ex13-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex14-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex14-code-editor`)), session)
output$`tutorial-exercise-ex14-output` <- renderUI({
  `tutorial-exercise-ex14-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex15-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex15-code-editor`)), session)
output$`tutorial-exercise-ex15-output` <- renderUI({
  `tutorial-exercise-ex15-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ex16-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ex16-code-editor`)), session)
output$`tutorial-exercise-ex16-output` <- renderUI({
  `tutorial-exercise-ex16-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.8"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106]}},"value":[{"type":"character","attributes":{},"value":["abind","assertthat","backports","base","boot","bslib","cem","checkmate","colorspace","combinat","compiler","crayon","curl","dagitty","datasets","DBI","digest","dplyr","ellipsis","evaluate","fansi","farver","fastmap","generics","ggdag","ggforce","ggplot2","ggraph","ggrepel","glue","graphics","graphlayouts","grDevices","grid","gridExtra","gtable","highr","htmltools","htmlwidgets","httpuv","httr","igraph","jquerylib","jsonlite","kableExtra","knitr","labeling","later","lattice","learnr","lifecycle","magrittr","markdown","MASS","MatchIt","Matrix","methods","mime","munsell","nlme","optmatch","pillar","pkgconfig","polyclip","promises","purrr","R6","randomForest","Rcpp","RItools","rlang","rmarkdown","rprojroot","rstudioapi","rvest","sass","scales","shiny","SparseM","splines","stats","stringi","stringr","survival","svd","svglite","systemfonts","tcltk","tibble","tidygraph","tidyr","tidyselect","tools","tweenr","utf8","utils","V8","vctrs","viridis","viridisLite","webshot","withr","xfun","xml2","xtable","yaml"]},{"type":"character","attributes":{},"value":["1.4-5","0.2.1","1.2.1","4.0.3","1.3-25","0.2.5.1","1.1.27","2.0.0","2.0-1","0.0-8","4.0.3","1.4.1","4.3.1","0.3-1","4.0.3","1.1.1","0.6.27","1.0.6","0.3.2","0.14","0.5.0","2.1.0","1.1.0","0.1.0","0.2.3","0.3.3","3.3.3","2.0.5","0.9.1","1.4.2","4.0.3","0.7.1","4.0.3","4.0.3","2.3","0.3.0","0.9","0.5.1.1","1.5.3","1.6.1","1.4.2","1.2.6","0.1.4","1.7.2","1.3.4","1.33","0.4.2","1.2.0","0.20-41","0.10.1","1.0.0","2.0.1","1.1","7.3-53","4.1.0","1.3-0","4.0.3","0.10","0.5.0","3.1-151","0.9-13","1.6.1","2.0.3","1.10-0","1.2.0.1","0.3.4","2.5.0","4.6-14","1.0.6","0.1-17","0.4.11","2.8","2.0.2","0.13","1.0.0","0.4.0","1.1.1","1.6.0","1.81","4.0.3","4.0.3","1.6.2","1.4.0","3.2-11","0.5","2.0.0","1.0.2","4.0.3","3.1.2","1.2.0","1.1.3","1.1.1","4.0.3","1.0.2","1.2.1","4.0.3","3.4.2","0.3.8","0.6.1","0.4.0","0.5.2","2.4.2","0.23","1.3.2","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">HDAT9700: Matching for Causal Inference</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
